description: >
  Setup the full environment in octopus required for deploying a Helm based Project. Requires environment variables
  for OCTOPUS_HOST and OCTOPUS_APIKEY. We recommend
  these be saved in a Project (https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project)
  or in Contexts (https://circleci.com/docs/2.0/contexts).

executor: <<parameters.executor>>

parameters:
  executor:
    description: executor to use for this job
    type: executor
    default: default

  space-name:
    description: Name of the space in octopus.
    type: string
    default: "Default"

  octopus-host:
    description: >
      Name of the environment variable which holds octopus host value.
    type: env_var_name
    default: OCTOPUS_HOST

  octopus-apikey:
    description: >
      Name of the environment variable which holds octopus apikey value.
    type: env_var_name
    default: OCTOPUS_APIKEY

  space-description:
    description: Octopus space description
    type: string

  is-default:
    type: boolean
    description: IsDefault
    default: false

  task-queue-stopped:
    type: boolean
    description: TaskQueueStopped variable

  space-managers-team-members:
    type: string
    description: Comma separated list of space Managers Team Members
    default: "teams-managers"

  space-managers-teams:
    type: string
    description: A comma-separated string containing list of space managers teams
    default: "teams-managers"

  env-name:
    description: >
      A comma-separated string containing list of environment name.
    type: string

  env-description:
    description: >
      A comma-separated string containing list of environment description .
    type: string

  env-sort-order:
    description: >
      A comma-separated string containing list of environment sort order value.
    type: string

  env-use-guided-failure:
    type: string
    description: >
      A comma-separated string containing list of environment UseGuidedFailure.

  allow-dynamic-infrastructure:
    description: A comma-separated string containing list of environment allowDynamicInfrastructure.
    type: string

  account-name:
    description: A comma-separated string containing list of account name.
    type: string

  account-description:
    description: A comma-separated string containing list of account description.
    type: string

  account-type:
    description: A comma-separated string containing list of account type.
    type: string

  account-token:
    description: A comma-separated string containing list of Environment Variable Name for account Token.
    type: string

  machine-name:
    description: A comma-separated string containing list of machine name.
    type: string

  machine-role:
    description: A comma-separated string containing list of machine role.
    type: string

  tenanted-deployment-participation:
    description: A comma-separated string containing list of machine tenantedDeploymentParticipation.
    type: string

  mac-communication-style:
    description: A comma-separated string containing list of machine CommunicationStyle.
    type: string

  cluster-url:
    description: A comma-separated string containing list of machine cluster url.
    type: string

  authentication-type:
    description: A comma-separated string containing list of machine AuthenticationType.
    type: string

  skip-tls-verification:
    description: A comma-separated string containing list of machine SkipTlsVerification.
    type: string

  action-template-name:
    description: A comma-separated string containing list of action template name.
    type: string

  action-template-description:
    description: A comma-separated string containing list of action template description.
    type: string

  action-template-type:
    description: A comma-separated string containing list of action template type.
    type: string

  lifecycle-name:
    description: A lifecycle name.
    type: string
  
  lifecycle-description:
    description: A lifecycle description.
    type: string

  lifecycle-automatic-targets:
    description: A comma separated list of environment in a lifecycle in which application deploy automatically.
    type: string

  lifecycle-optional-targets:
    description: A comma separated list of environment in a lifecycle in which application can deploy optionally.
    type: string

  lifecycle-phases-order:
    description: A comma separated list of environment in order of lifecycle execution.
    type: string

  feed-name:
    description: Name of the feed
    type: string

  feed-type:
    description: Feed Type
    type: string

  feed-url:
    description: Feed Url
    type: string

  feed-username:
    description: Feed Username
    type: string

  feed-password:
    description: Name of the environment variable hodling the value of feed password.
    type: string
  


steps:
  - install-prerequisite:
  - run:
      name: Configure Octopus Environment
      command: |
        ./bin/k8socopus --cmd configureOctopus --spaceName <<parameters.space-name>> --envNameArr <<parameters.env-name>> --clusterUrlArr <<parameters.cluster-url> --lifecycleName <<parameters.lifecycle-name>> --phasesOrder <<parameters.lifecycle-phases-order>> --automaticTargets <<parameters.lifecycle-automatic-targets>> --optionalTargets <<parameters.lifecycle-optional-targets>> --feedName <<parameters.feed-name>> --feedUri <<parameters.feed-url>> --atNameArr <<parameters.action-template-name>> --actionTemplateTypeArr <<parameters.action-template-type>>